### ISSUE TITLE
Doc request: why locations-api v.s. OSPlaces API?

### ISSUE THREAD

**Issue by RichardBradley** [alphagov/locations-api#147]
Hi,

I'm working on a GOV.UK project that uses OSPlaces API. The OSPlaces support team mentioned this project to us.

Your main README doesn't currently explain what benefits the `locations-api` project offers over the OSPlaces API or why a GOV project might choose to connect to you v.s. connecting to OSPlaces directly. I think that would be useful info if you could add it?

Also, if we were to use it, would we look to connect to a proxy server hosted centrally, or would we need to host our own server running the `locations-api` app? And if the former, how would hosting costs and maintenance / SLAs be handled?

Thanks,

Rich

**Comment by KludgeKML** [comment]
Hi Rich,

The main benefit to GOV.UK applications is that locations-api smooths out requests and provides caching and update control, which means applications using it don't have to worry about the rate-limit on the OS Places API (locations-api's background workers keep everything updated and keep the rate of requests well below safe numbers). Our API adapter also provides a simplified method for calling it from other GOV.UK ruby applications. Your project may or may not benefit from those features, depending on where it's running and what language it's being built in.

If your project is to run inside the main GOV.UK infrastructure, it would be simplest to use the existing server (and then of course hosting and maintenance costs are irrelevant). If outside, either connecting to our server our hosting your own would probably be possible, although we might have to investigate the security issues of calling in, and SLAs would probably have to be negotiated specifically.

I've dropped you an email if you want to contact me directly to provide more information that might help us work out what the best option is for you.

Keith

**Comment by RichardBradley** [comment]
Thanks for your reply, that makes sense.

You might want to add this info to your README to assist future developers who are referred to this project.

I will reply by email about the project specific aspects.

**Comment by KludgeKML** [comment]
Marking as closed.
